apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Email для уведомлений от Let's Encrypt (например, об истечении сертификата)
    email: dmitry_stepanov@inbox.ru
    # URL тестовой среды Let's Encrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Имя секрета, где будет храниться ключ аккаунта Let's Encrypt
      name: letsencrypt-staging-key
    # Метод подтверждения владения доменом. HTTP01 - самый простой.
    solvers:
    - http01:
        ingress:
          class: istio
