apiVersion: v1
kind: Service
metadata:
  name: postgres-service # В переменной окружения ConnectionStrings__DefaultConnection бэкенда хост должен быть postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # Сервис доступен только внутри кластера