apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # echo -n 'your_postgres_user' | base64
  POSTGRES_USER: cG9zdGdyZXM=
  # echo -n 'your_super_secret_password' | base64
  POSTGRES_PASSWORD: QWxmYV9iYW5rXzAwN3Bvc3RncmVz
